dist: trusty
script: "/bin/true"
notifications:
  email: false
  slack:
    secure: WxfskWF2ZKX7e30mC/vRN9A8t99tNZ2KuwjHTTHkEj47GerHW8a5YdKZ2Do5LhfG8SezDzk0XiAq7PQzsK+NXzztJt6eko2GVOsYnDETwHTarKYIST0J0UdU1H2AO7N3a7gIQYuQZ36bPlBw0ODFu5UmDmG8lnSoHa9uNROcvbpNTCCutSr9giwzawULYcS+ZQoxk0FUZ9dWgCssNRg1RPLFlm2VzgBfkiZFdG7411hN7mMTCEGK6t39Dcuy2oU96whcfJ0ljBPLfcmtgkg9nNpqsk7uW6b1InI4jP9o/Q287/Xr/D/0iSPOpB0NGwuosUGHbXfSijtyjBy4oNgHpSlvg+eJjpD6j8vFmQL2k3v4lZQMeLL3dUWcFTy9vt6bPHXql/ioz2vbIRwFTvh6U2/vjg/oyoUwecwprhl5BpmXREP5kc4D9ITwhbne+YQpZIwbjbv+248SDamVdDQ8cqhL0aZJn7nt0jvef+fVufOn70L9XfRtE+o18TCwdvhpOCAiLqvzRhawy9hH0z5/Qykg1EIx9rLhDCb7xGndR+dvIXJ/X5U8Q3S/Lt+h6qPW/Me7ZqddHRod73x3PqwnXUd3oObEkePohNlEu1QAhd+hS1rbeAl2TfMpBgn1VlzKmArraTxOrwGMrnUGolcPUEzGMUhCP7RJsnV1k1et8hI=
